### ISSUE TITLE
Cannot read property 'length' of undefined after Role gets created 

### ISSUE THREAD

**Issue by ruben-qb** [maximivanov/aws-iam-copy-role#1]
Role got created but no policies got attached. I'm not very good with node. Would be of great help if you could assist. 

StackTrace: 

--> Parsing arguments from command line...
<-- Arguments loaded. Source role name: role-1, target role name: role-2

--> Checking if AWS credentials are loaded...
<-- AWS credentials found.

--> Fetching source role...
<-- Source role loaded.

--> Fetching inline policy names for role-1...
<-- Loaded 0 inline policy names.

--> Fetching managed policies for role-1...
<-- Loaded 9 managed policies.

--> Creating a new role role-2...
<-- Created role role-2.

< IMAGE HERE >

Cannot read property 'length' of undefined

Node version:  v14.14.0

**Comment by ruben-qb** [comment]
Couple of typos in inline policy function. Please do a cleanup. 

Thanks anyway !

**Comment by jplandry908** [comment]
For anyone else is having this issue, you can resolve it by tweaking this line of code:

```
if (inlinePolicies.length > 0) {
	await addInlinePolicies(targetRoleName, inlinePolicies)
}

if (managedPolicies.length > 0) {
	await addManagedPolicies(targetRoleName, managedPolicies)
}
```

and changing to:

```
if (inlinePolicies && inlinePolicies.length > 0) {
	await addInlinePolicies(targetRoleName, inlinePolicies)
}

if (managedPolicies && managedPolicies.length > 0) {
	await addManagedPolicies(targetRoleName, managedPolicies)
}
```

Basically if the inlinePolicies or managedPolicies variables are undefined, the IF statement fails. This checks to see if it is undefined prior to checking the length.

**Comment by maximivanov** [comment]
Thanks @ruben-qb for reporting the problem and @jplandry908 for the suggested fix.

It looks like the problem was caused by this part in `fetchInlinePolicies`:

```js
    if (inlinePolicyNames.length === 0) {
        return
    }
```

i.e. it was returning undefined while it should have returned an empty array. I just fixed it in https://github.com/maximivanov/aws-iam-copy-role/commit/330e8f31dee0fc989c030c20399a9ee6e15aa0f8 and additional checks as in `if (inlinePolicies && inlinePolicies.length > 0) {` should be no longer necessary.

It appears `fetchManagedPolicies` didn't have this problem.
