### ISSUE TITLE
fetchmanagedpoliciesrecursive should call self, calls other

### ISSUE THREAD

**Issue by EvanWMorton** [maximivanov/aws-iam-copy-role#2]
In copy-role.js, `fetchmanagedpoliciesrecursive` calls `fetchinlinepoliciesrecursive` rather than calling itself recursively.  The simplest fix is presumably just to replace the call with a recursive call.

There is an alternative.  In both of these functions, using iteration rather than recursion would IMO be simpler.  And it would be impossible to make the specific mistake that occurred, and any similar mistake would come out more easily in test.  So an alternative fix would be to use iteration instead.

**Comment by maximivanov** [comment]
Hey @EvanWMorton thanks for reaching out and sorry it took so long to reply. It's clearly a mistyped reference - I think it will hard fail if it gets into the `fetchManagedPoliciesRecursive` since the referenced function is out of scope there.

I guess recursion over iteration is a personal preference.

Anyway, the code is updated. Cheers!
